---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.14
  commands:
  - go build -v -a -o release/linux/amd64/drone-covergates
